default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: pretty-format-json
        name: Format json files
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [ --fix, --config=pyproject.toml ]
      - id: ruff-format
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        types: [python]
        # uncomment and add other mypy tying packages
        # as needed
        # additional_dependencies:
        #   - "pydantic>=2.5.2"

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
